# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, verbose_name='用户统一ID')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='设备标识')),
                ('apns_token', models.CharField(blank=True, max_length=100, verbose_name='苹果推送Token')),
            ],
        ),
    ]
