# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0003_accountinfo_reject_tone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceMsgList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='相关用户UID')),
                ('channel', models.CharField(max_length=30, verbose_name='频道名')),
                ('status', models.IntegerField(choices=[(0, '初始化'), (1, '已获取'), (2, '已完成')], default=0, verbose_name='状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
