# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0004_voicemsglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemsglist',
            name='uid',
            field=models.CharField(max_length=30, verbose_name='相关用户UID'),
        ),
    ]
