# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0005_auto_20200113_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='reject_tone',
            field=models.TextField(blank=True, verbose_name='拒接电话语音'),
        ),
    ]
