# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-01 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0006_auto_20200118_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemsglist',
            name='extra_msg',
            field=models.TextField(blank=True, verbose_name='额外信息'),
        ),
    ]
