# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0007_voicemsglist_extra_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_uid', models.CharField(max_length=30, verbose_name='拨打用户')),
                ('dst_uid', models.TextField(verbose_name='接收用户')),
                ('call_time', models.DateTimeField(verbose_name='拨打时间')),
            ],
        ),
    ]
