# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-13 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.jsonable


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0010_calltask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_uid', models.CharField(max_length=30, verbose_name='拨打用户')),
                ('dst_uid', helpers.director.model_func.cus_fields.jsonable.JsonAbleField(verbose_name='接收用户')),
                ('channel', models.CharField(max_length=30, verbose_name='通话频道')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('refreshtime', models.DateTimeField(blank=True, null=True, verbose_name='心跳刷新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='calltask',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '初始'), (1, '已经拨打')], default=0, verbose_name='状态'),
        ),
    ]
