# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0011_auto_20200213_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='count',
            field=models.IntegerField(default=0, verbose_name='人员计数'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='is_robot',
            field=models.BooleanField(default=False, verbose_name='是否机器人'),
        ),
        migrations.AlterField(
            model_name='voicemsglist',
            name='status',
            field=models.IntegerField(choices=[(0, '未接通'), (1, '已完成')], default=0, verbose_name='状态'),
        ),
    ]
