# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0012_auto_20200213_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True, verbose_name='上报用户')),
                ('channel', models.CharField(max_length=30, verbose_name='通话频道')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='事件编码')),
                ('desp', models.TextField(blank=True, verbose_name='时间描述')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='产生时间')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maindb.CallRecord')),
            ],
        ),
        migrations.AlterField(
            model_name='voicemsglist',
            name='status',
            field=models.IntegerField(choices=[(0, '未接通'), (1, '已接通'), (2, '已挂断')], default=0, verbose_name='状态'),
        ),
    ]
