# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0014_auto_20200214_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='api地址')),
                ('content', models.TextField(help_text='json字符串', verbose_name='返回内容')),
            ],
        ),
        migrations.AlterField(
            model_name='callevent',
            name='desp',
            field=models.TextField(blank=True, verbose_name='事件描述'),
        ),
    ]
