# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-25 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0015_auto_20200222_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltask',
            name='taskid',
            field=models.IntegerField(default=0, help_text='app后台的任务ID', verbose_name='任务id'),
        ),
    ]
