# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.jsonable


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0016_calltask_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltask',
            name='call_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拨打时间'),
        ),
        migrations.AlterField(
            model_name='calltask',
            name='dst_uid',
            field=helpers.director.model_func.cus_fields.jsonable.JsonAbleField(default=[], verbose_name='接收用户'),
        ),
    ]
