# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0017_auto_20200225_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callevent',
            name='uid',
            field=models.CharField(default='', max_length=30, verbose_name='上报用户'),
            preserve_default=False,
        ),
    ]
