# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0018_auto_20200227_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='callevent',
            name='sender_type',
            field=models.IntegerField(choices=[(0, '用户上报'), (1, '机器人上报')], default=0, verbose_name='上报类型'),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='uid',
            field=models.CharField(max_length=30, verbose_name='相关用户'),
        ),
    ]
