# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-04 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0019_auto_20200304_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRtcMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=30, verbose_name='频道名称')),
                ('uid', models.CharField(max_length=30, verbose_name='用户名称')),
                ('rtcid', models.IntegerField(verbose_name='RTC映射ID')),
            ],
        ),
    ]
