# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-06 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.plain_file


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0020_userrtcmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='KEY')),
                ('url', helpers.director.model_func.cus_fields.plain_file.PlainFileField(max_length=300, verbose_name='文件路径')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
