# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0021_frontlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='call_group',
            field=models.IntegerField(default=0, verbose_name='拨打组'),
        ),
    ]
