# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-20 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0022_callrecord_call_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='channel',
            field=models.CharField(max_length=30, unique=True, verbose_name='通话频道'),
        ),
    ]
