# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-26 22:53
from __future__ import unicode_literals

from django.db import migrations
import helpers.director.model_func.cus_fields.plain_file


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0023_auto_20200320_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='record_file',
            field=helpers.director.model_func.cus_fields.plain_file.PlainFileField(blank=True, max_length=300, verbose_name='录音音频'),
        ),
    ]
