# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindb', '0024_callrecord_record_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemsglist',
            name='is_robot',
            field=models.BooleanField(default=False, verbose_name='是否机器人'),
        ),
    ]
